### ISSUE TITLE
missing older image tag

### ISSUE THREAD

**Issue by dnevencm** [bodsch/docker-mysql#7]
ERROR: docker_image[bodsch/docker-mysql] (cmoc-docker::monitoring-data-collection line 17) had an error: Docker::Error::NotFoundError: manifest for bodsch/docker-mysql:1711.2 not found

Image is not longer available in dockerhub.

tag is also unavailable as github tag to rebuild ourself

**Comment by bodsch** [comment]
the 1711.2 had a gross error in the initial database creation.
especially in the cloud environment he often appeared.
fixed bug with version 1711.3

I recommend bodsch/docker-mysql:1711.4 or bodsch/docker-mysql:10.1.28-r1.
